### ISSUE TITLE
Data mapping to and from template step is not possible 

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#4777]
## This is a...

<pre><code>
[ ] Feature request
[ x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

There is this demo of the template step: https://www.youtube.com/watch?v=Pfysm8W8sco&t=0s

Following the steps (just used DB search instead of twitter search), the mapping step ignores the specified template step - is only possible to map to the last step of the integration.

## Expected behavior
The user should be able to map to the template step

## Screenshot

![out](https://user-images.githubusercontent.com/4180208/53887856-6a1f9b00-4023-11e9-9b9a-3579aae582ea.gif)

## Tasks involved / Steps to Reproduce

1. Start creating new integration - e.g. DB -> gmail
2. Specify template step in between -> use mustache as the template type
3. Try to create mapping in front of the template step
4. The mapping is not possible

**Comment by heiko-braun** [comment]
@phantomjinx Can you take a look at this? @christophd might be able to provide advice ...

**Comment by gashcrumb** [comment]
@tplevko it'd be good to also attach an export that we could use as a starting point.

**Comment by gashcrumb** [comment]
I'll take a peek too, this logic is handled in the data mapper host component and could require some adjusting.

**Comment by gashcrumb** [comment]
Strange, I followed the flow here from the gif but I was indeed able to map the output of the split step to the template step.  Using a build from slightly earlier this morning EST.

**Comment by gashcrumb** [comment]
@phantomjinx @christophd maybe it'd be good to double-check which behavior you see when you get a chance?

**Comment by christophd** [comment]
Just put this to a test with latest master and I can not reproduce that behavior. I see a good chance that this has been fixed with #4618 

@tplevko can you please have another look?

**Comment by phantomjinx** [comment]
Looked at this for most of the afternoon and pulled from latest master and I cannot replicate it. Adding the datamapper after adding the template-step correctly loads the 'Template JSON Schema' as the datamapper target. 
My thoughts:
- Is it possible that the datamapper was added before the template-step then removed then (as per the video) the template-step added then the datamapper re-added?
- I notice the template syntax of {{company}} is coloured black and not purple, the latter being the correct colour for a symbol if the codemirror lint-ing is working correctly. If the editor is not working correctly then maybe the json-schema has not been constructed (empty?)

As a sidenote, I noticed my lint-ing was not working. This was due to having run yarn inside node_modules/ng2-codemirror and ending up with another install of codemirror (5.22.0) at node_modules/ng2-codemirror/node_modules/codemirror. Yes, this made my brain explode and may be completely irrelevant but thought I would document it, just in case.

@gashcrumb @tplevko

**Comment by gashcrumb** [comment]
Yeah, it feels like there could be some path to reproducing this that we're missing.  Also it's worth double-checking that the lint functionality is working properly, especially if having the correct data shape for the template step relies on that.  @phantomjinx would you be able to further investigate that part, and maybe @tplevko can see if he can still reproduce it and just fully document the sequence of steps leading to the issue?

**Comment by tplevko** [comment]
Tried with newest master and it seems work correctly again. I didn't do any additional steps when recording the gif, so maybe @christophd is right and it got fixed with the mentioned PR. I think we can close this. 

@phantomjinx the syntax highlight is still missing, should we open a new issue for that?

**Comment by phantomjinx** [comment]
@tplevko @gashcrumb 
Checked out syntax highlighting again this morning and works for development but not in compiled images. Have opened a new issue to this effect -> https://github.com/syndesisio/syndesis/issues/4802
