### ISSUE TITLE
Issue trying to Save an integration

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#6506]
## This is a...

<pre><code>
[ ] Feature request
[*] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
2019-09-04 14:03:09.609 ERROR [-,5bb57e6d302df4b8,5bb57e6d302df4b8,false] 1 --- [  XNIO-3 task-9] .s.e.v.h.e.SyndesisServerExceptionMapper : Internal Server Exception. managementUrl
java.lang.NullPointerException: managementUrl
	at java.util.Objects.requireNonNull(Objects.java:228) ~[na:1.8.0_201]
	at io.syndesis.common.model.integration.ImmutableIntegrationOverview$Builder.managementUrl(ImmutableIntegrationOverview.java:3618) ~[common-model-1.8-SNAPSHOT.jar!/:1.8-SNAPSHOT]
	at io.syndesis.server.endpoint.v1.handler.integration.IntegrationOverviewHelper.toCurrentIntegrationOverview(IntegrationOverviewHelper.java:133) ~

Also when I'm able to save it, clicking on stop exposing via 3scale blows up my server, and I've now lost my integration.

**Comment by zregvart** [comment]
@rkorytkowski perhaps it would make sense to be a bit more robust about this. Otherwise we might also need a configuration migration script.

**Comment by KurtStam** [comment]
I just reinstalled and I still see the issue
<img width="1067" alt="Screen Shot 2019-09-04 at 10 51 00 PM" src="https://user-images.githubusercontent.com/35576/64290635-bdd55780-cf66-11e9-8b55-ecc7b8aa1cba.png">

**Comment by KurtStam** [comment]
'Do not expose via 3scale' results in the above error. I think in the project 3scale should not be the default btw.

<img width="817" alt="Screen Shot 2019-09-04 at 10 54 39 PM" src="https://user-images.githubusercontent.com/35576/64290760-fd9c3f00-cf66-11e9-8ad5-b098dcdbaab8.png">

**Comment by rkorytkowski** [comment]
Thanks. I'm on it.

**Comment by zregvart** [comment]
@rkorytkowski feel free to reach out to @dongniwang on UX guidance for the issue @KurtStam noted in https://github.com/syndesisio/syndesis/issues/6506#issuecomment-528083212

**Comment by rkorytkowski** [comment]
Fixed NPE in #6520.

@KurtStam, 3scale should be the default exposure only, if you set the OPENSHIFT_MANAGEMENT_URL_FOR3SCALE  environment variable for the syndesis-server deployment. Do you have it set? It shouldn't be set by default.

@dongniwang, do you have any comments regarding wording for the two options in the screenshot? 'Manage in 3scale' takes you to the 3scale configuration, whereas 'Do not expose via 3scale' disables 3scale integration. More background on https://github.com/syndesisio/syndesis/issues/3708

**Comment by KurtStam** [comment]
@rkorytkowski it appears the value is set to `<no value>' nowadays:

    - name: OPENSHIFT_MANAGEMENT_URL_FOR3SCALE
      value: <no value>

That maybe causing this.

**Comment by rkorytkowski** [comment]
I thought I had operator running, but it wasn't updated :/ I'll fix it ASAP.

**Comment by rkorytkowski** [comment]
@zregvart, do you happen to know, if I setup syndesis from a template and do not pass OPENSHIFT_MANAGEMENT_URL_FOR_3SCALE variable, will it default to "" or some strange value like operator did i.e. `<no value>`?

**Comment by KurtStam** [comment]
@rkorytkowski I'm pretty sure it wasn't set before while now with the operator it's set to `<no value>`. Also I'm still seeing

2019-09-05 09:28:49.971 ERROR [-,d44c20b10c8a61ce,d44c20b10c8a61ce,false] 1 --- [  XNIO-3 task-4] .s.e.v.h.e.SyndesisServerExceptionMapper : Internal Server Exception. managementUrl
java.lang.NullPointerException: managementUrl
	at java.util.Objects.requireNonNull(Objects.java:228) ~[na:1.8.0_201]
	at io.syndesis.common.model.integration.ImmutableIntegrationOverview$Builder.managementUrl(ImmutableIntegrationOverview.java:3618) ~[common-model-1.8-SNAPSHOT.jar!/:1.8-SNAPSHOT]
	at io.syndesis.server.endpoint.v1.handler.integration.IntegrationOverviewHelper.toCurrentIntegrationOverview(IntegrationOverviewHelper.java:133) ~[server-endpoint-1.8-SNAPSHOT.jar!/:1.8-SNAPSHOT]
	at io.syndesis.server.endpoint.v1.handler.integration.IntegrationHandler.lambda$list$2(IntegrationHandler.java:211) ~[server-endpoint-1.8-SNAPSHOT.jar!/:1.8-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_201]
	at java.util.Collections$2.tryAdvance(Collections.java:4717) ~[na:1.8.0_201]
	at java.util.Collections$2.forEachRemaining(Collections.java:4725) ~[na:1.8.0_201]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_201]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_201]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_201]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_201]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_201]
	at io.syndesis.server.endpoint.v1.handler.integration.IntegrationHandler.list(IntegrationHandler.java:212) ~[server-endpoint-1.8-SNAPSHOT.jar!/:1.8-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140) ~[resteasy-jaxrs-3.6.1.Final.jar!/:3.6.1.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:509) ~[resteasy-jaxrs-3.6.1.Final.jar!/:3.6.1.Final]

**Comment by rkorytkowski** [comment]
@KurtStam, I can no longer reproduce. Are you sure you are running the latest? 

The fix for the operator is in #6523.

**Comment by KurtStam** [comment]
In my environment I have manually undefined the `OPENSHIFT_MANAGEMENT_URL_FOR3SCALE` param.

the commit id of the server is:
Commit ID:
2612ce5b4687d744f5f6c5894b7462096b2db694

So I think that includes your fix.

**Comment by rkorytkowski** [comment]
Nope, the fix is one commit later 9c9ea666.

**Comment by KurtStam** [comment]
Yep - NPE is fixed. thx

**Comment by KurtStam** [comment]
Cool - @dongniwang, can you comment on
https://github.com/syndesisio/syndesis/issues/6506#issuecomment-528083212

**Comment by dongniwang** [comment]
@rkorytkowski @zregvart @KurtStam thanks for tagging me! 

@rkorytkowski - would it be possible for you to provide a demo of the workflow so I can understand better how the buttons work and what users should expect when interacting with these controls? 

@TovaCohen would be a great resource to go to for wording related questions. 

I'm happy to set up a meeting to follow up on this.

**Comment by rkorytkowski** [comment]
Yes, let's have a quick call. Please do include anyone interested.

**Comment by gaughan** [comment]
Is this moved to Jira? @heiko-braun 
The buttons above should just be one setting/button, "Discover is either true or false"

**Comment by rkorytkowski** [comment]
@gaughan Thanks! There are distinct buttons, because "Manage in 3scale" takes you to the 3scale instance to configure the endpoint, whereas "Do not expose via 3scale" disables 3scale and exposes the endpoint as a basic route. We'll have a quick UX chat with @dongniwang on Wednesday. I've included you in the invite, if you are interested.
